
CMD_WRITE_LED_ALL      = 10

CMD_MOTOR_SET          = 20
CMD_MOTOR_SPEED_READ   = 21
CMD_MOTOR_SPEED_READ_R = 128 + CMD_MOTOR_SPEED_READ
CMD_MOTOR_ENC_READ     = 22
CMD_MOTOR_ENC_READ_R   = 128 + CMD_MOTOR_ENC_READ

CMD_ENC_READ         = 30
CMD_ENC_READ_R       = 128+CMD_ENC_READ

CMD_CBARRE_SCAN      = 40
CMD_CBARRE_SCAN_R    = 128 + CMD_CBARRE_SCAN
CMD_CBARRE_READ      = 41
CMD_CBARRE_READ_R    = 128 + CMD_CBARRE_READ

CMD_GOTO             = 50
CMD_MOVE             = 51
CMD_ROTATE           = 52

CMD_GO               = 60
CMD_GO_R             = 128 + CMD_GO

CMD_ODO_RESET        = 70

CMD_LOG_RT           = 100
CMD_LOG_RT_R         = 128 + CMD_LOG_RT

CMD_DEBUG            = 255
CMD_DEBUG_R          = 255

# Real Time Log id
RTLOG_ENCODER_0      = 0
RTLOG_ENCODER_0_MASK = 1<<RTLOG_ENCODER_0
RTLOG_ENCODER_1      = 1
RTLOG_ENCODER_1_MASK = 1<<RTLOG_ENCODER_1
RTLOG_ODOMETER_X     = 2
RTLOG_ODOMETER_X_MASK = 1<<RTLOG_ODOMETER_X
RTLOG_ODOMETER_Y     = 3
RTLOG_ODOMETER_Y_MASK = 1<<RTLOG_ODOMETER_Y
RTLOG_ODOMETER_A     = 4
RTLOG_ODOMETER_A_MASK = 1<<RTLOG_ODOMETER_A

RTLOG_FAST_BARCODE        = 5
RTLOG_FAST_BARCODE_MASK   = 1<<RTLOG_FAST_BARCODE
RTLOG_FAST_ENCODER_0      = 6
RTLOG_FAST_ENCODER_0_MASK = 1<<RTLOG_FAST_ENCODER_0
RTLOG_FAST_ENCODER_1      = 7
RTLOG_FAST_ENCODER_1_MASK = 1<<RTLOG_FAST_ENCODER_1

RTLOG_OVERFLOW       = 1<<7


